# Generated by Django 3.1.7 on 2021-04-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_auto_20210418_2236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='urlManager',
        ),
        migrations.RenameField(
            model_name='urlshortner',
            old_name='timestamp',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='urlshortner',
            name='updated',
        ),
        migrations.AlterField(
            model_name='urlshortner',
            name='output',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
